# Generated by Django 2.2.10 on 2022-07-17 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0030_auto_20211226_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 11, 3, 27, 981319, tzinfo=utc)),
        ),
    ]
