# Generated by Django 2.2.10 on 2022-07-17 11:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0031_auto_20220717_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='end_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 11, 16, 4, 205622, tzinfo=utc)),
        ),
    ]
